"""added image url column

Revision ID: 52ecf8cb6d52
Revises: d09b4af1eae4
Create Date: 2025-02-18 19:25:26.392608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ecf8cb6d52'
down_revision = 'd09b4af1eae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menuitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menuitem', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
