"""Fix owner_menu_id in menuitem

Revision ID: 57395c6e70f7
Revises: 269713171ef8
Create Date: 2025-02-21 00:05:14.172133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57395c6e70f7'
down_revision = '269713171ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menuitem', schema=None) as batch_op:
        batch_op.alter_column('owner_menu_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menuitem', schema=None) as batch_op:
        batch_op.alter_column('owner_menu_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
