"""Initial neondb migration

Revision ID: 5f0f1daecfff
Revises: 
Create Date: 2025-03-24 13:03:12.527938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0f1daecfff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ownermenu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('cuisine', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('waiting', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menuitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_menu_id', sa.Integer(), nullable=True))
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint('menuitem_outlet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'outlet', ['outlet_id'], ['id'])
        batch_op.create_foreign_key(None, 'ownermenu', ['owner_menu_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_customer', type_='foreignkey')
        batch_op.drop_constraint('fk_orders_outlet', type_='foreignkey')
        batch_op.drop_constraint('fk_orders_table', type_='foreignkey')
        batch_op.create_foreign_key(None, 'outlet', ['outlet_id'], ['id'])
        batch_op.create_foreign_key(None, 'table_bookings', ['table_booking_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['customer_id'], ['id'])

    with op.batch_alter_table('outlet', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint('outlet_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('table_bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_table_bookings_customer', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_table_bookings_customer', 'users', ['customer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('outlet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('outlet_owner_id_fkey', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_orders_table', 'table_bookings', ['table_booking_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_orders_outlet', 'outlet', ['outlet_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_orders_customer', 'users', ['customer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('menuitem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('menuitem_outlet_id_fkey', 'outlet', ['outlet_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('owner_menu_id')

    op.drop_table('ownermenu')
    # ### end Alembic commands ###
