"""Added description to ownermenu

Revision ID: c5056bc8d24a
Revises: e3e3b7bb9fb4
Create Date: 2025-02-23 20:05:34.734453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5056bc8d24a'
down_revision = 'e3e3b7bb9fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ownermenu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ownermenu', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
