"""Made owner_menu_id null in menuitem

Revision ID: d31b46028a5c
Revises: abfa9269b08c
Create Date: 2025-02-21 21:53:54.528407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31b46028a5c'
down_revision = 'abfa9269b08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menuitem', schema=None) as batch_op:
        batch_op.alter_column('owner_menu_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menuitem', schema=None) as batch_op:
        batch_op.alter_column('owner_menu_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
